include: package:lints/recommended.yaml

formatter: 
  page_width: 320
  trailing_commas: preserve

linter:  
  rules:
    avoid_print: false
    always_specify_types: true
    always_use_package_imports: true
    directives_ordering: true
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
