name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  

  csm_view:
    path: ../

  csm_client_core: 
    git:
      url: https://github.com/Cosmos-CSM/csm_client
      path: csm_client_core/

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  lints: ^6.0.0

flutter:
  uses-material-design: true
