name: csm_view
description: A package to improve view development for csm applications.
version: 3.0.0
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets: 
    - 'assets/'
    - 'assets/business/'